---
# dev-build.yml

- name: Build Configurations and Documentation # (1)!
  hosts: ANDREAS_DEV_FABRIC
  gather_facts: false
  tasks:

    - name: Generate AVD Structured Configurations and Fabric Documentation # (2)!
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
      vars:
        output_dir: ./dev_intended
#        output_dir_base: ./dev_intended
        structured_config_dir: "{{ output_dir }}/structured_configs"
        documentation_dir: "./dev_documentation" # Changed this line
        documentation_subdir: "fabric" # Added this line

    - name: Generate Device Configurations and Documentation # (3)!
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
      vars:
        output_dir: ./dev_intended
#        output_dir_base: ./dev_intended
        intended_configs_dir: "{{ output_dir }}/configs"
        documentation_dir: "./dev_documentation" # Changed this line
        documentation_subdir: "devices" # Added this line

